from sqlalchemy.schema import Column
from sqlalchemy.types import String, Integer
from database import Base
class CarInfo(Base):
    __tablename__ = "property_point_view"
    # id = Column(Integer, primary_key=True, index=True)
    X =  Column(String)
    Y =  Column(String)
    OBJECTID = Column(Integer, primary_key=True, index=True)
    FOLIO = Column(String)
    TTRRSS = Column(String)
    X_COORD = Column(String)
    Y_COORD = Column(String)
    TRUE_SITE_ADDR = Column(String)
    TRUE_SITE_UNIT = Column(String)
    TRUE_SITE_CITY = Column(String)
    TRUE_SITE_ZIP_CODE = Column(String)
    TRUE_MAILING_ADDR1 = Column(String)
    TRUE_MAILING_ADDR2 = Column(String)
    TRUE_MAILING_ADDR3 = Column(String)
    TRUE_MAILING_CITY = Column(String)
    TRUE_MAILING_STATE = Column(String)
    TRUE_MAILING_ZIP_CODE = Column(String)
    TRUE_MAILING_COUNTRY = Column(String)
    TRUE_OWNER1 = Column(String)
    TRUE_OWNER2 = Column(String)
    TRUE_OWNER3 = Column(String)
    CONDO_FLAG = Column(String)
    PARENT_FOLIO = Column(String)
    DOR_CODE_CUR = Column(String)
    DOR_DESC = Column(String)
    SUBDIVISION = Column(String)
    BEDROOM_COUNT = Column(String)
    BATHROOM_COUNT = Column(String)
    HALF_BATHROOM_COUNT = Column(String)
    FLOOR_COUNT = Column(String)
    UNIT_COUNT = Column(String)
    BUILDING_ACTUAL_AREA = Column(String)
    BUILDING_HEATED_AREA = Column(String)
    LOT_SIZE = Column(String)
    YEAR_BUILT = Column(String)
    ASSESSMENT_YEAR_CUR = Column(String)
    ASSESSED_VAL_CUR = Column(String)
    DOS_1 = Column(String)
    PRICE_1 = Column(String)
    LEGAL = Column(String)
    PID = Column(String)
    DATEOFSALE_UTC = Column(String)

   

